/*
 * Loan Service API
 *
 * This is a simple server to create and get information about Loan service.
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InstallmentResponseInstallments struct {

	Month int32 `json:"month,omitempty"`

	DueDate string `json:"dueDate,omitempty"`

	Capital string `json:"capital,omitempty"`

	Interest string `json:"interest,omitempty"`

	Total string `json:"total,omitempty"`
}
